# Основная конфигурация
SessionTimeout = 14400
TimeZone = "Europe/Moscow"
Mode = "dev"

[Lg]
Info = true
Notice = true
Warning = true
Error = true
Critical = true
Fatal = true
Traces = true
OutStd = true
OutFile = true
OutHttp = ""

[Workflow]
Limitch = 1000      # буфер канала задач
Limitpool = 9       # максимальное количество воркеров обслуживающих задачи
